>>> lazy_matrix_mul = __import__("101-lazy_matrix_mul").lazy_matrix_mul
>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])
>>> lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
array([[13, 16]])
>>> lazy_matrix_mul([[10, 20], [30, 40]], [[7, 1, 3], [4, 2, 9]])
array([[150,  50, 210],
       [370, 110, 450]])
>>> lazy_matrix_mul([[1, 9], [3, 4]], [[6, 9], [5, 2], [1, 3]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)
>>> lazy_matrix_mul(120, [[6, 9], [5, 2], [1, 3]])
array([[ 720, 1080],
       [ 600,  240],
       [ 120,  360]])
>>> lazy_matrix_mul([[1, 9], [3, 4]], 120)
array([[ 120, 1080],
       [ 360,  480]])
>>> lazy_matrix_mul(120.00, [[6, 9], [5, 2], [1, 3]])
array([[ 720., 1080.],
       [ 600.,  240.],
       [ 120.,  360.]])
>>> lazy_matrix_mul([[1, 9], [3, 4]], 120.00)
array([[ 120., 1080.],
       [ 360.,  480.]])
>>> lazy_matrix_mul(([1, 2]), [[3, 4], [5, 6]])
array([13, 16])
>>> lazy_matrix_mul(([1, 2],), [[3, 4], [5, 6]])
array([[13, 16]])
>>> lazy_matrix_mul([[1, 2]], ([3, 4], [5, 6]))
array([[13, 16]])
>>> lazy_matrix_mul({"a": 1, "b": 2}, [[3, 4], [5, 6]])
Traceback (most recent call last):
TypeError: unsupported operand type(s) for *: 'dict' and 'int'
>>> lazy_matrix_mul([[1, 2]], {"c": [3, 4], "d": [5, 6]})
Traceback (most recent call last):
TypeError: unsupported operand type(s) for *: 'int' and 'dict'
>>> lazy_matrix_mul([], ([3, 4], [5, 6]))
Traceback (most recent call last):
ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)
>>> lazy_matrix_mul([[10, 20], [30, 40]], [])
Traceback (most recent call last):
ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)
>>> lazy_matrix_mul([(1, 2)], [[3, 4], [5, 6]])
array([[13, 16]])
>>> lazy_matrix_mul([[1, 2]], [[3, 4], (5, 6)])
array([[13, 16]])
>>> lazy_matrix_mul([[10, 20], []], [[7, 1, 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[], [30, 40]], [[7, 1, 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[10, 20], [30, 40]], [[], [4, 2, 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[10, 20], [30, 40]], [[7, 1, 3], []])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[10.00, 20.0], [30, 40]], [[7, 1, 3], [4.00, 2.00, 9]])
array([[150.,  50., 210.],
       [370., 110., 450.]])
>>> lazy_matrix_mul([[10, 20], [30.0, 40.00]], [[7.00, 1, 3.00], [4, 2, 9.00]])
array([[150.,  50., 210.],
       [370., 110., 450.]])
>>> lazy_matrix_mul([[10, "Alpha"], [30, 40]], [[7, 1, 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: data type must provide an itemsize
>>> lazy_matrix_mul([[10, 20], ["Alpha", 40]], [[7, 1, 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: data type must provide an itemsize
>>> lazy_matrix_mul([[10, 20], [30, 40]], [[7, "Beta", 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: data type must provide an itemsize
>>> lazy_matrix_mul([[10, 20], [(30,35), 40]], [[7, "Beta", 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence
>>> lazy_matrix_mul([[10, 20], [30, 40]], [[7, 1, 3], [4, {"a": 1, "b": 2}, 9]])
Traceback (most recent call last):
TypeError: unsupported operand type(s) for *: 'int' and 'dict'
>>> lazy_matrix_mul([[10, 20], [[30, 35], 40]], [[7, 1, 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[10, 20], [30, 40]], [[7, 1, 3], [4, [1, 2], 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[10, 20], [30, 40, 50]], [[7, 1, 3], [4, 2, 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[10, 20], [30, 40]], [[7, 1, 3], [4, 2, 9, 10]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
